# Generated by Django 5.2.16 on 2026-07-13 12:39

import django.db.models.deletion
import uuid
import wiki.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=60, unique=True)),
                ('color', models.CharField(default='#64748b', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WikiNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('folder', '폴더'), ('page', '페이지')], default='page', max_length=12)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('draft', '초안'), ('published', '게시됨')], db_index=True, default='draft', max_length=12)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_batch', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wiki_nodes', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_wiki_nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wiki.wikinode')),
                ('tags', models.ManyToManyField(blank=True, related_name='nodes', to='wiki.tag')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_wiki_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('template', models.CharField(default='default', max_length=50)),
                ('search_text', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='wiki.wikinode')),
            ],
            options={
                'ordering': ('node__title',),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(height_field='height', upload_to=wiki.models.asset_upload_path, width_field='width')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=80)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('alt_text', models.CharField(blank=True, max_length=240)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_assets', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='wiki.wikinode')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('blocks', models.JSONField(default=list)),
                ('properties', models.JSONField(default=dict)),
                ('template', models.CharField(default='default', max_length=50)),
                ('status', models.CharField(choices=[('draft', '초안'), ('published', '게시됨')], max_length=12)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_revisions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wiki.pagecontent')),
            ],
            options={
                'ordering': ('-created_at', '-number'),
                'constraints': [models.UniqueConstraint(fields=('page', 'number'), name='unique_page_revision_number')],
            },
        ),
        migrations.AddIndex(
            model_name='wikinode',
            index=models.Index(fields=['parent', 'is_deleted', 'position'], name='wiki_wikino_parent__2e6108_idx'),
        ),
        migrations.AddIndex(
            model_name='wikinode',
            index=models.Index(fields=['kind', 'status', 'is_deleted'], name='wiki_wikino_kind_2294ab_idx'),
        ),
        migrations.AddIndex(
            model_name='wikinode',
            index=models.Index(fields=['-updated_at'], name='wiki_wikino_updated_a99e6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='wikinode',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0)), name='wiki_node_position_nonnegative'),
        ),
    ]
