# Generated by Django 5.2.16 on 2026-07-13 12:46

from django.db import migrations, models


def backfill_public_snapshots(apps, schema_editor):
    PageContent = apps.get_model("wiki", "PageContent")
    PageRevision = apps.get_model("wiki", "PageRevision")
    for content in PageContent.objects.select_related("node").iterator():
        if content.node.status == "published":
            content.published_blocks = content.blocks
            content.published_properties = content.properties
            content.published_template = content.template
            content.published_search_text = content.search_text
            content.save(
                update_fields=(
                    "published_blocks",
                    "published_properties",
                    "published_template",
                    "published_search_text",
                )
            )
    for revision in PageRevision.objects.select_related("page__node").iterator():
        revision.summary = revision.page.node.summary
        revision.parent_node_id = revision.page.node.parent_id
        revision.save(update_fields=("summary", "parent_node_id"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='draft_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='published_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='published_properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='published_search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='published_template',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='pagerevision',
            name='parent_node_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagerevision',
            name='summary',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.RunPython(backfill_public_snapshots, noop_reverse),
    ]
